name: Josiah Alter Photo Co.
favicon: null
layout_spectrum: 0.1494088782928884
typography_spectrum: 0.21864554402418435
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020200'
    - '#fefefe'
    - '#abc1cc'
    - '#758791'
    - '#fe841d'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.5164642254821956
purpose: []
